"""add test_run status for async grading

Revision ID: 853338f92d35
Revises: d022b2232db4
Create Date: 2026-08-27 11:48:31.880352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853338f92d35'
down_revision = 'd022b2232db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        # server_default backfills every pre-existing row (all historical
        # runs already have full results) as 'done'; new rows created
        # through the ORM get 'pending' from the model's Python-side
        # default instead (server/models/test_run.py), so this is only
        # ever exercised for the one-time backfill here.
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False, server_default='done'))
        batch_op.alter_column('passed_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('results_json',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.alter_column('results_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('total_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('passed_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
