"""add escalating grader cooldown streak

Revision ID: ce8ab82a7560
Revises: 9d2387e5c722
Create Date: 2026-08-29 17:45:51.485930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8ab82a7560'
down_revision = '9d2387e5c722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (NOT NULL with no default
    # otherwise fails against a table that already has data).
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grader_run_streak', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('grader_run_streak')

    # ### end Alembic commands ###
