"""add class is_archived

Revision ID: ef96c230de9a
Revises: ce8ab82a7560
Create Date: 2026-08-30 15:18:29.051548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef96c230de9a'
down_revision = 'ce8ab82a7560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (NOT NULL with no default
    # otherwise fails against a table that already has data).
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
